server:
  port: 8080

logging:
  level: 
    '[reactor.netty.http.client]': debug
    # '[com.alibaba.nacos]': debug
    '[org.springframework.cloud.gateway]': debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan}:%clr(%L){magenta} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  charset:
    console: UTF-8
    file: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://13.51.85.43:3000}"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: false
      routes:
        - id: user_service_route
          # uri: ${USER_SERVICE_URL}  # http://user-service:8081
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: chat_service_route
          # uri: ${CHAT_SERVICE_URL}    http://chat-service:8082
          uri: http://localhost:8082
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@inMemoryRateLimiter}"
                key-resolver: "#{@ipKeyResolver}"
                replenish-rate: 10000
                burst-capacity: 100000
                requested-tokens: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
