-- ----------------------------
-- 用户表 (user)
-- ----------------------------
-- DROP TABLE IF EXISTS `user` IF EXISTS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '加密后的密码',
  `nickname` VARCHAR(255) NOT NULL COMMENT '用户昵称',
  `email` VARCHAR(255) NOT NULL COMMENT '用户邮箱',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_username` ON `user`(`username`);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_email` ON `user`(`email`);
COMMENT ON TABLE `user` IS '用户表';

-- ----------------------------
-- 问答历史表 (chat_history)
-- ----------------------------
-- DROP TABLE IF EXISTS `chat_history` IF EXISTS;
CREATE TABLE IF NOT EXISTS `chat_history` (
  `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `question` CLOB NOT NULL COMMENT '用户提出的问题',
  `answer` CLOB COMMENT 'AI返回的回答',
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '问答时间戳',
  `session_id` VARCHAR(255) NOT NULL COMMENT '会话ID',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);
CREATE INDEX IF NOT EXISTS `idx_user_id` ON `chat_history`(`user_id`);
COMMENT ON TABLE `chat_history` IS '问答历史表';

