server:
  port: 8081
spring:
  application:
    name: user-service
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: 3.101.113.38:8848
  #       #ip: 127.0.0.1
  #       #port: 8081

  ## H2
  # datasource:
  #     url: jdbc:h2:tcp://localhost:9092/ai_chat_system;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
  #     driverClassName: org.h2.Driver
  #     username: sa
  #     password: 
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  #     settings:
  #       web-allow-others: false

  ## mysql
  datasource:
    url: jdbc:mysql://database:3306/ai_chat_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Zaq12wsxcde3
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api/user/v3/api-docs
    config-url: /api/user/v3/api-docs/swagger-config
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true    

logging:
  level: 
    root: info
    '[com.ai.chat.service]': debug
    # '[com.alibaba.nacos]': info
    '[org.springframework.cloud]': info
    '[org.hibernate.sql]': debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan}:%clr(%L){magenta} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log
  charset:
    console: UTF-8
    file: UTF-8    
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"    

jwt:
  secret: HhyD5jnwwGbyecOrbkAY6OEWNM/zDgF2qwFlF4MFAHznR4AaLweF8Xu71MF4TaYUfX7dRY9JIzOgF/yTYqx5Qg==
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: WHEN_AUTHORIZED
    info:
      enabled: true
    metrics:
      enabled: false
  metrics:
    enable:
      process: false
      system: false
